### ISSUE TITLE
Unable to play SmoothStream video

### ISSUE THREAD

**Issue by stevewadsworth** [Orange-OpenSource/hasplayer.js#104] opened 2016-05-11 17:53 UTC
We have a Smooth+PlayReady stream that plays fine in the Silverlight player, but not in hasplayer.
This is on Windows 10 in both Edge and IE11.

It appears to parse the manifest, aquire the license key and start reading the fragments but then reports an error:

[BufferController][video] Error with segment data, no bytes to push 

The JS I'm using is pretty much exactly from the example:

```
var context = new MediaPlayer.di.Context();
var player = new MediaPlayer(context);
player.startup();
player.getDebug().setLevel(4);
player.attachView(document.querySelector("#videoPlayer"));
player.addEventListener("error", onError);
player.attachSource(url);
```

A fuller log transcript follows (URL's obfuscated):

```
Setting video url
has.html (15,13)
[18:31:22.836][StreamController] load url: http://myserver/05RL54EY9CZ3_encrypted.ism/manifest 
hasplayer.js (7241,21)
[18:31:23.286][ManifestLoader] Manifest downloaded 
hasplayer.js (7245,21)
[18:31:23.289][MssParser] Doing parse. 
hasplayer.js (7241,21)
[18:31:23.320][MssParser] Parsing complete (xmlParser: 7ms, mss2dash: 23ms, total: 0.03s) 
hasplayer.js (7241,21)
[18:31:23.331][StreamController] Manifest has loaded. 
hasplayer.js (7241,21)
[18:31:23.421][Stream] Create MediaSource 
hasplayer.js (7245,21)
[18:31:23.422][Stream] Setup MediaSource 
hasplayer.js (7245,21)
[18:31:23.442][Stream] <video> loadstart event 
hasplayer.js (7241,21)
[18:31:23.452][Stream] Initialize MediaSource 
hasplayer.js (7245,21)
[18:31:23.586][Stream] Video codec: video/mp4;codecs="avc1.4D4029" 
hasplayer.js (7241,21)
[18:31:23.632][BufferController][video] Initialize 
hasplayer.js (7245,21)
[18:31:23.633][BufferController][video] updateData 
hasplayer.js (7245,21)
[18:31:23.636][Stream] checkIfInitialized videoState=ready audioState=null textTrackState=null 
hasplayer.js (7245,21)
[18:31:23.654][Stream] Audio codec: audio/mp4;codecs="mp4a.40.2" 
hasplayer.js (7241,21)
[18:31:23.663][BufferController][audio] Initialize 
hasplayer.js (7245,21)
[18:31:23.664][BufferController][audio] updateData 
hasplayer.js (7245,21)
[18:31:23.668][Stream] checkIfInitialized videoState=ready audioState=ready textTrackState=null 
hasplayer.js (7245,21)
[18:31:23.731][Stream] checkIfInitialized videoState=ready audioState=ready textTrackState=ready 
hasplayer.js (7245,21)
[18:31:23.731][DRM] Initialize ProtectionController (video/mp4;codecs="avc1.4D4029", audio/mp4;codecs="mp4a.40.2") 
hasplayer.js (7245,21)
[18:31:23.732][DRM] Get supported key systems from content protection 
hasplayer.js (7245,21)
[18:31:23.733][DRM] Select key system 
hasplayer.js (7245,21)
[18:31:23.734][DRM][3Feb2014] Request access for key system com.microsoft.playready 
hasplayer.js (7245,21)
[18:31:23.766][DRM][3Feb2014] configuration supported = audio:[{"contentType":"audio/mp4;codecs=\"mp4a.40.2\""}], video:[{"contentType":"video/mp4;codecs=\"avc1.4D4029\""}] 
hasplayer.js (7245,21)
[18:31:23.768][DRM] KeySystem Access (com.microsoft.playready) Granted!  Selecting key system... 
hasplayer.js (7245,21)
[18:31:23.769][DRM][3Feb2014] Select key system com.microsoft.playready 
hasplayer.js (7245,21)
[18:31:23.867][DRM] KeySystem selected => create key session 
hasplayer.js (7245,21)
[18:31:23.868][DRM] Create key session 
hasplayer.js (7245,21)
[18:31:23.868][DRM][3Feb2014] Create key session 
hasplayer.js (7245,21)
[18:31:23.885][DRM] Session created.  SessionID =  
hasplayer.js (7245,21)
[18:31:23.887][Stream] No text tracks. 
hasplayer.js (7245,21)
[18:31:23.890][DRM] Key added 
hasplayer.js (7245,21)
[18:31:23.929][Stream] Initialize playback 
hasplayer.js (7245,21)
[18:31:23.938][EventController] Added 0 inline events 
hasplayer.js (7245,21)
[18:31:23.942][Stream] Setting duration: 132.569093 
hasplayer.js (7245,21)
[18:31:23.944][Stream] <video> durationchange event: 132.569093 
hasplayer.js (7241,21)
[18:31:23.948][AbrController][video] Check rules.... 
hasplayer.js (7245,21)
[18:31:23.973][Stream] Playback initialized 
hasplayer.js (7245,21)
[18:31:23.975][AbrController][audio] Check rules.... 
hasplayer.js (7245,21)
[18:31:23.985][DownloadRatioRule][video] Checking download ratio rule... (current = 0) 
hasplayer.js (7245,21)
[18:31:23.986][DownloadRatioRule][video]No requests made for this stream yet, bailing. 
hasplayer.js (7245,21)
[18:31:24.002][AbrController][video] Request for quality 999, priority = 0.5 
hasplayer.js (7245,21)
[18:31:24.003][AbrController][video] Request for quality 999, priority = 0.5 
hasplayer.js (7245,21)
[18:31:24.008][AbrController][video] Set quality: 0 
hasplayer.js (7241,21)
[18:31:24.010][DownloadRatioRule][audio] Checking download ratio rule... (current = 0) 
hasplayer.js (7245,21)
[18:31:24.011][DownloadRatioRule][audio]No requests made for this stream yet, bailing. 
hasplayer.js (7245,21)
[18:31:24.016][AbrController][video] Set playback quality: 0 
hasplayer.js (7245,21)
[18:31:24.031][AbrController][audio] Request for quality 999, priority = 0.5 
hasplayer.js (7245,21)
[18:31:24.031][AbrController][audio] Request for quality 999, priority = 0.5 
hasplayer.js (7245,21)
[18:31:24.037][AbrController][audio] Set quality: 0 
hasplayer.js (7241,21)
[18:31:24.039][DashHandler][video] getCurrentTime =>  0 
hasplayer.js (7245,21)
[18:31:24.041][AbrController][audio] Set playback quality: 0 
hasplayer.js (7245,21)
[18:31:24.043][Stream] Start time = 0 
hasplayer.js (7241,21)
[18:31:24.043][Stream] Seek: 0 
hasplayer.js (7241,21)
[18:31:24.044][Stream] startBuffering at time 0 
hasplayer.js (7245,21)
[18:31:24.044][BufferController][video] SEEK: 0 
hasplayer.js (7241,21)
[18:31:24.046][BufferController][audio] SEEK: 0 
hasplayer.js (7241,21)
[18:31:24.053][BufferController][video] START 
hasplayer.js (7241,21)
[18:31:24.053][BufferController][video] startPlayback 
hasplayer.js (7241,21)
[18:31:24.054][BufferController][video] stalled = true 
hasplayer.js (7241,21)
[18:31:24.054]<video> setPlaybackRate(0) 
hasplayer.js (7241,21)
[18:31:24.055][BufferController][video] Check buffer... 
hasplayer.js (7245,21)
[18:31:24.055][BufferController][video] Working time = 0, Buffer level = 0.000 
hasplayer.js (7245,21)
[18:31:24.056][BufferController][video] BUFFERING - 0 - 0 
hasplayer.js (7245,21)
[18:31:24.056][BufferController][video] time to end = 132.569093 
hasplayer.js (7245,21)
[18:31:24.057][BufferController][video] Start buffering process... 
hasplayer.js (7245,21)
[18:31:24.059][Stream] <video> ratechange event: 0 
hasplayer.js (7241,21)
[18:31:24.062][BufferController][audio] START 
hasplayer.js (7241,21)
[18:31:24.063][BufferController][audio] startPlayback 
hasplayer.js (7241,21)
[18:31:24.063][BufferController][audio] stalled = true 
hasplayer.js (7241,21)
[18:31:24.063]<video> setPlaybackRate(0) 
hasplayer.js (7241,21)
[18:31:24.064][BufferController][audio] Check buffer... 
hasplayer.js (7245,21)
[18:31:24.064][BufferController][audio] Working time = 0, Buffer level = 0.000 
hasplayer.js (7245,21)
[18:31:24.065][BufferController][audio] BUFFERING - 0 - 0 
hasplayer.js (7245,21)
[18:31:24.065][BufferController][audio] time to end = 132.569093 
hasplayer.js (7245,21)
[18:31:24.066][BufferController][audio] Start buffering process... 
hasplayer.js (7245,21)
[18:31:24.069][AbrController][video] Check rules.... 
hasplayer.js (7245,21)
[18:31:24.076][AbrController][audio] Check rules.... 
hasplayer.js (7245,21)
[18:31:24.180][DownloadRatioRule][video] Checking download ratio rule... (current = 0) 
hasplayer.js (7245,21)
[18:31:24.181][DownloadRatioRule][video]No requests made for this stream yet, bailing. 
hasplayer.js (7245,21)
[18:31:24.297][DownloadRatioRule][audio] Checking download ratio rule... (current = 0) 
hasplayer.js (7245,21)
[18:31:24.298][DownloadRatioRule][audio]No requests made for this stream yet, bailing. 
hasplayer.js (7245,21)
[18:31:24.302][AbrController][video] Request for quality 999, priority = 0.5 
hasplayer.js (7245,21)
[18:31:24.303][AbrController][video] Request for quality 999, priority = 0.5 
hasplayer.js (7245,21)
[18:31:24.309][AbrController][video] Set quality: 0 
hasplayer.js (7241,21)
[18:31:24.313][AbrController][audio] Request for quality 999, priority = 0.5 
hasplayer.js (7245,21)
[18:31:24.313][AbrController][audio] Request for quality 999, priority = 0.5 
hasplayer.js (7245,21)
[18:31:24.329][AbrController][video] Set playback quality: 0 
hasplayer.js (7245,21)
[18:31:24.332][BufferController][video] currentDownloadQuality changed : 0 
hasplayer.js (7245,21)
[18:31:24.333][BufferController][video] Send RepresentationSwitch with quality = 0 
hasplayer.js (7245,21)
[18:31:24.335][AbrController][audio] Set quality: 0 
hasplayer.js (7241,21)
[18:31:24.338][AbrController][audio] Set playback quality: 0 
hasplayer.js (7245,21)
[18:31:24.341][DRM] Get supported key systems from content protection 
hasplayer.js (7245,21)
[18:31:24.350][BufferController][audio] currentDownloadQuality changed : 0 
hasplayer.js (7245,21)
[18:31:24.351][BufferController][audio] Send RepresentationSwitch with quality = 0 
hasplayer.js (7245,21)
[18:31:24.357][DRM] Get supported key systems from content protection 
hasplayer.js (7245,21)
[18:31:24.379][BufferController][video] Load request  0 
hasplayer.js (7241,21)
[18:31:24.414][BufferController][video] Initialization loaded  0 
hasplayer.js (7245,21)
[18:31:24.417][BufferController][audio] Load request  0 
hasplayer.js (7241,21)
[18:31:24.421][BufferController][video] Buffer initialization segment  0 
hasplayer.js (7241,21)
[18:31:24.423][BufferController][audio] Initialization loaded  0 
hasplayer.js (7245,21)
[18:31:24.431][BufferController][audio] Buffer initialization segment  0 
hasplayer.js (7241,21)
[18:31:24.459][BufferController][video] Buffering segment 
hasplayer.js (7245,21)
[18:31:24.531][BufferController][audio] Buffering segment 
hasplayer.js (7245,21)
[18:31:24.542][Stream] <video> durationchange event: 132.569093 
hasplayer.js (7241,21)
[18:31:24.543][Stream] <video> loadedmetadata event 
hasplayer.js (7241,21)
[18:31:24.565][BufferController][video] Segment buffered 
hasplayer.js (7245,21)
[18:31:24.566][BufferController][video] set currentBufferedQuality to 0 
hasplayer.js (7245,21)
[18:31:24.568][Stream] Check start time 
hasplayer.js (7241,21)
[18:31:24.582][BufferController][video] Initialization segment buffered 
hasplayer.js (7245,21)
[18:31:24.583][BufferController][video] loadNextFragment for time: 0 
hasplayer.js (7245,21)
[18:31:24.583][DashHandler][video] Getting the request for time: 0 
hasplayer.js (7245,21)
[18:31:24.597][BufferController][audio] Segment buffered 
hasplayer.js (7245,21)
[18:31:24.598][BufferController][audio] set currentBufferedQuality to 0 
hasplayer.js (7245,21)
[18:31:24.599][Stream] Check start time 
hasplayer.js (7241,21)
[18:31:24.602][BufferController][audio] Initialization segment buffered 
hasplayer.js (7245,21)
[18:31:24.602][BufferController][audio] loadNextFragment for time: 0 
hasplayer.js (7245,21)
[18:31:24.603][DashHandler][audio] Getting the request for time: 0 
hasplayer.js (7245,21)
[18:31:24.664][DashHandler][video] getIndexForSegments for time  0 
hasplayer.js (7245,21)
[18:31:24.664][DashHandler][video] getIndexForSegments, idx =   0 
hasplayer.js (7245,21)
[18:31:24.670][DashHandler][video] Index for time 0 is 0 
hasplayer.js (7245,21)
[18:31:24.672][DashHandler][audio] getIndexForSegments for time  0 
hasplayer.js (7245,21)
[18:31:24.673][DashHandler][audio] getIndexForSegments, idx =   0 
hasplayer.js (7245,21)
[18:31:24.680][DashHandler][audio] Index for time 0 is 0 
hasplayer.js (7245,21)
[18:31:24.765][BufferController][video] Load request  http://myserver/05RL54EY9CZ3_encrypted.ism/QualityLevels(597000)/Fragments(video_eng=0) 
hasplayer.js (7241,21)
[18:31:24.766][FragmentLoader][video] Load: http://myserver/05RL54EY9CZ3_encrypted.ism/QualityLevels(597000)/Fragments(video_eng=0) 
hasplayer.js (7245,21)
[18:31:24.783][BufferController][audio] Load request  http://myserver/05RL54EY9CZ3_encrypted.ism/QualityLevels(128016)/Fragments(audio=0) 
hasplayer.js (7241,21)
[18:31:24.785][FragmentLoader][audio] Load: http://myserver/05RL54EY9CZ3_encrypted.ism/QualityLevels(128016)/Fragments(audio=0) 
hasplayer.js (7245,21)
[18:31:24.891][FragmentLoader][video] Loaded: http://myserver/05RL54EY9CZ3_encrypted.ism/QualityLevels(597000)/Fragments(video_eng=0) (200, 123ms, 3ms) 
hasplayer.js (7245,21)
[18:31:24.899][BufferController][video] Media loaded  http://myserver/05RL54EY9CZ3_encrypted.ism/QualityLevels(597000)/Fragments(video_eng=0) 
hasplayer.js (7245,21)
[18:31:24.929][BufferController][video] Error with segment data, no bytes to push 
hasplayer.js (7233,21)
[18:31:24.930][BufferController][video] Check buffer... 
hasplayer.js (7245,21)
[18:31:24.930][BufferController][video] Working time = 0, Buffer level = 0.000 
hasplayer.js (7245,21)
[18:31:24.931][BufferController][video] time to end = 132.569093 
hasplayer.js (7245,21)
[18:31:24.931][BufferController][video] Start buffering process... 
hasplayer.js (7245,21)
[18:31:24.959][AbrController][video] Check rules.... 
hasplayer.js (7245,21)
[18:31:24.981][DownloadRatioRule][video] Checking download ratio rule... (current = 0) 
hasplayer.js (7245,21)
[18:31:24.982][DownloadRatioRule][video] DL: 0.003s, Total: 0.126s 
hasplayer.js (7241,21)
[18:31:24.982][DownloadRatioRule][video] BW = 417 kb/s 
hasplayer.js (7241,21)

```

**Comment by bbert** [comment] 2016-05-12 09:09
Hi,

```
[18:31:24.899][BufferController][video] Media loaded  http://myserver/05RL54EY9CZ3_encrypted.ism/QualityLevels(597000)/Fragments(video_eng=0) 
hasplayer.js (7245,21)
[18:31:24.929][BufferController][video] Error with segment data, no bytes to push 
```

There is an issue with your downloaded segment. The received segment was empty. Network issue?

**Comment by stevewadsworth** [comment] 2016-05-12 10:30
The same stream plays fine in Silverlight (https://playready.directtaps.net/pr/doc/slee/) on the same machine so while not impossible, I don't think it's a network problem.
The network tab in Edge is reporting reasonable sizes for the Fragments, taking time to download and not reporting an error but it is not showing anything in the response body tab.

I can share the manifest URL if that would help.

**Comment by stevewadsworth** [comment] 2016-05-12 10:53
Wireshark is showing lots of video/mp4 data being returned in the fragment requests.

**Comment by bbert** [comment] 2016-05-12 11:51
Yes, please share your manifest URL so that we can have a look.

**Comment by stevewadsworth** [comment] 2016-05-12 11:55
I have emailed two URL's to you directly. Thank you for your assistance.

**Comment by stevewadsworth** [comment] 2016-05-12 14:18
After further investigation we have found the stream contains a box of type “subs”. This type is unknown to the hasplayer and so mp4lib.boxes.ContainerBox.prototype.read
Throws an error which results in the  BufferController onMediaLoaded function getting  null value for the data and thus no playing.

Fudging  the hasplayer to ignore this error results in the stream playing.

We are not familiar with the structure of the streams and didn't generate these streams so we are not sure if this box type can safely be ignored or even what it is for.

**Comment by bbert** [comment] 2016-05-12 14:23
OK, I see. I haven't had yet time to look at your stream.
Butn there may be some issue with unknown boxes. For unkown box types we should simply either remove or let it as it is, but we should not throw an error.
We will correct this.

**Comment by nicosang** [comment] 2016-05-13 13:53
I think the problem is resolved by the pull request : #106 .

**Comment by stevewadsworth** [comment] 2016-05-16 10:37
For some reason I couldn't build the development branch following the instructions.
I cherry-picked the fix onto master and built it there and it does fix the issue we were seeing.

Thank you for the quick fix!

Do you have an estimate of when this will make it into a release?

**Comment by nicosang** [comment] 2016-05-17 08:11
this task is in our to do list :-) I think it will be done next week

**Comment by stevewadsworth** [comment] 2016-05-18 08:36
Awesome.
Thanks for the support.

**Comment by danrossi** [comment] 2016-06-02 06:32
Confirming IE11 on Windows 10 does not play. Edge browser is fine however. It sits at this console log

[16:30:54.009][BufferController][audio] Working time = 0, Buffer level = 0.000

**Comment by nicosang** [comment] 2016-06-07 08:21
Could you test again on IE11 with the development branch? it seems that we had a bug on IE11 :-(

**Comment by danrossi** [comment] 2016-06-07 11:32
confirming this is fixed in IE11 on Windows 10.

**Closed** 2016-06-07 12:18 UTC
